name: "Repo Summary Action"
description: "A GitHub Action to summarize repo activity with Gemini AI"
inputs:
  github_token:
    description: "The GitHub token for API access."
    required: true
  gemini_api_key:
    description: "The Gemini API key for summarization."
    required: true
  repo_owner:
    description: "The owner of the repository."
    required: true
  repo_name:
    description: "The name of the repository."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"