name: Generate Repo Digest

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs once every night at midnight UTC

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run repo summary action
        id: summary-action
        uses: ./action.yml # Points to your JavaScript action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}