name: Generate Repo Digest
permissions:
  discussions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the crucial new step
      - name: Install dependencies
        run: npm install
        working-directory: ./ # Make sure to point to the correct directory
      
      - name: Build the action
        run: npm run build
        working-directory: ./ # Ensure this is the correct path to your action

      - name: Run repo summary action
        id: summary-action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          # Uncomment and configure the following lines to enable email distribution:
          # email_enabled: "true"
          # smtp_host: "smtp.gmail.com"
          # smtp_port: "587"
          # smtp_user: ${{ secrets.SMTP_USER }}
          # smtp_password: ${{ secrets.SMTP_PASSWORD }}
          # from_email: "digest@yourorg.com"
          # from_name: "Weekly Repository Digest"