name: Generate Repo Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the crucial new step
      - name: Install dependencies
        run: npm install
        working-directory: ./path/to/your/action # Make sure to point to the correct directory

      - name: Run repo summary action
        id: summary-action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}